
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: sfl
      POSTGRES_PASSWORD: sflpass
      POSTGRES_DB: sfl
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  pgdata:
